version: '3.8'

services:
  web-server:
    build: ./web-custom
    container_name: althea-web
    ports:
      - "80:80"
    restart: always
    networks:
      - althea-net

  db-patient:
    image: postgres:15
    container_name: althea-db
    environment:
      - POSTGRES_PASSWORD=Administrateur123*
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - althea-net

networks:
  althea-net:
    driver: bridge

volumes:
  db-data:
