version: '3.8'

services:
  # Service Web (Nginx)
  web-server:
    build: ./web-custom
    container_name: althea-web
    ports:
      - "80:80"
    restart: always
    networks:
      - althea-net # Réseau isolé (Critère Orchestration)
    depends_on:
      - db-patient

  # Service Base de données (PostgreSQL)
  db-patient:
    image: postgres:15
    container_name: althea-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data # Persistance (Critère Persistance)
    networks:
      - althea-net

networks:
  althea-net:
    driver: bridge # Réseau privé pour isoler la DB du web

volumes:
  db-data: # Volume pour ne pas perdre les données patients
