services:

  # Conteneur 1 : Le site Web Althea

  web-server:

    image: nginx:latest

    ports:

      - "80:80"

    restart: always


  # Conteneur 2 : La base de données (données patients)

  db-patient:

    image: postgres:15

    environment:

      POSTGRES_PASSWORD: Administrateur123*

    restart: always
