version: '3.8'

services:
  # Service Web Front-End
  web-server:
    build: ./web-custom
    container_name: althea-web
    ports:
      - "80:80"
    restart: always
    networks:
      - althea-net
    depends_on:
      - db-patient

  # Service Base de données
  db-patient:
    image: postgres:15
    container_name: althea-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - althea-net

# Configuration du réseau privé
networks:
  althea-net:
    driver: bridge

# Configuration de la persistance des données
volumes:
  db-data:
